name: Daily Commit

on:
  schedule:
    - cron: '30 14 * * *'  # Runs daily at 14:30 UTC
  workflow_dispatch:  # Optional manual trigger

jobs:
  commit_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Make a trivial change
        run: |
          # Add a timestamp so every run produces a new commit
          echo "Daily update $(date +%s)" >> daily_update.txt

      - name: Configure Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "24f2007572@ds.study.iitm.ac.in"

      - name: Commit and push changes — 24f2007572@ds.study.iitm.ac.in
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git add daily_update.txt
          git commit -m "Daily update from GitHub Action $(date +%s)" || echo "No changes to commit"
          git push https://x-access-token:${PAT_TOKEN}@github.com/24f2007572-PJ/Daily_Update.git HEAD:main
